### ISSUE TITLE
Breaking Change: Microsoft.Web.Redis.ISerializer not present in v5.0.0

### ISSUE THREAD

**Issue by faraazaamir** [Azure/aspnet-redis-providers#194] opened 2023-06-05 22:28 UTC
We are using v4.0.1 and tried to upgrade to v5.0.0. However, since we are using JsonSerialization, we implemented the interface Microsoft.Web.Redis.ISerializer which was available in v4.0.1. However this interface is missing in v5.0.0 which renders it useless for us and are forced to be on v4.0.1.

Is there any other alternative?

**Comment by stanleysmall-microsoft** [comment] 2023-06-05 22:43
Closing as a duplicate of issue #185

**Closed by stanleysmall-microsoft** 2023-06-05 22:43 UTC
