### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SosaWISE** [Azure/aspnet-redis-providers#12] opened 2015-11-05 18:45 UTC
I am unable to install this package.  Not sure why.  I have a project that I just opened VS 2015 and has various NuGet packages and they all installed OK but this one.  Trying to install it through the Package Manager and I keep getting this error.  

I opened VS as the Administrator and still get the same error.  Below is the output.

> Attempting to gather dependencies information for package 'Microsoft.Web.RedisSessionStateProvider.1.6.5' with respect to project 'Client\XXXX.Admin.Host', targeting '.NETFramework,Version=v4.6'
> Attempting to resolve dependencies for package 'Microsoft.Web.RedisSessionStateProvider.1.6.5' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'Microsoft.Web.RedisSessionStateProvider.1.6.5'
> Resolved actions to install package 'Microsoft.Web.RedisSessionStateProvider.1.6.5'
> Install failed. Rolling back...
> Package 'Microsoft.Web.RedisSessionStateProvider 1.6.5' does not exist in project 'XXXX.Admin.Host'
> Package 'Microsoft.Web.RedisSessionStateProvider 1.6.5' does not exist in folder 'C:\DEV\Repos\XXXX.Admin\packages'
> System.NullReferenceException: **Object reference not set to an instance of an object.**
>    at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()

Below is a screen shot of installing it from Console:
![pmconsole](https://cloud.githubusercontent.com/assets/1862668/10980617/4a694dba-83c0-11e5-8a1b-8628c082c37b.PNG)

**Comment by SiddharthChatrolaMs** [comment] 2016-03-15 21:12
I am not sure what is wrong here. I tried same thing with VS 2015 and .NET 4.6 and it worked fine.
![untitled](https://cloud.githubusercontent.com/assets/8050630/13794189/df07a210-eab7-11e5-9dde-98778c425679.jpg)

**Comment by SiddharthChatrolaMs** [comment] 2016-07-27 21:43
This is duplicate of issue https://github.com/Azure/aspnet-redis-providers/issues/15

**Closed by SiddharthChatrolaMs** 2016-07-27 21:43 UTC
Labels: duplicate
