### ISSUE TITLE
Redis timeout issue

### ISSUE THREAD

**Issue by nileshpore** [Azure/aspnet-redis-providers#109] opened 2018-10-12 07:21 UTC
I am getting timeout issue with redis.

**Following is the exception**
System.TimeoutException: Timeout performing EVAL, inst: 1, mgr: ProcessReadQueue, err: never, queue: 7, qu: 0, qs: 7, qc: 0, wr: 0, wq: 0, in: 507, ar: 1, clientName: EG-APP04, serverEndpoint: Unspecified/####, keyHashSlot: 12598,  IOCP: (Busy=0,Free=1600,Min=800,Max=1600), WORKER: (Busy=187,Free=1413,Min=800,Max=1600), Local-CPU: unavailable 

 **Configuration: Connection string**
<add name="RedisConnectionString" connectionString="###,connectRetry=10, abortConnect=false, allowAdmin=true, ssl=false" />

Am I missing something?

**Comment by JonCole** [comment] 2018-10-12 16:18
Timeouts are typically caused by either a client side or server side resource limitation.  For example, hitting high CPU on client or server, hitting high memory conditions that result in page faulting (again, client side or server side, running expensive commands, etc.  I have a couple of posts that talk about things to look into when you see these issues.  Take a look at these and hopefully you can figure out what is going wrong.

[Client Side Debugging Tips](https://gist.github.com/JonCole/db0e90bedeb3fc4823c2#file-diagnoserediserrors-clientside-md)

[Server Side Debugging Tips](https://gist.github.com/JonCole/9225f783a40564c9879d#file-diagnoserediserrors-serverside-md)

**Comment by SiddharthChatrolaMs** [comment] 2018-12-06 17:21
There is no issue with session state provider so closing the issue

**Closed by SiddharthChatrolaMs** 2018-12-06 17:21 UTC

**Comment by wjdavis5** [comment] 2019-01-25 15:03
Sounds like there is enough  evidence to consider using multiple ConnectionMultiplexers for high traffic sites to help alleviate some of these issues.
