### ISSUE TITLE
ArgumentNullException: Buffer cannot be null. Parameter name: buffer

### ISSUE THREAD

**Issue by blusen-ip** [Azure/aspnet-redis-providers#207] opened 2023-08-31 19:20 UTC
Using Microsoft.Web.RedisSessionStateProvider v5.0.1 and targetFramework="net48"
On first access of session data the following exception is generated:

- Message: Buffer cannot be null. Parameter name: buffer
- Source: mscorlib
- ParamName: buffer
- Stack Trace:
```
o	at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
o	at System.IO.MemoryStream..ctor(Byte[] buffer)
o	at Microsoft.Web.Redis.StackExchangeClientConnection.DeserializeSessionStateItemCollection(RedisResult serializedSessionStateItemCollection)
o	at Microsoft.Web.Redis.StackExchangeClientConnection.GetSessionData(Object rowDataFromRedis)
o	at Microsoft.Web.Redis.RedisConnectionWrapper.TryTakeWriteLockAndGetData(DateTime lockTime, Int32 lockTimeout, Object& lockId, ISessionStateItemCollection& data, Int32& sessionTimeout)
o	at Microsoft.Web.Redis.RedisSessionStateProvider.GetItemFromSessionStore(Boolean isWriteLockRequired, HttpContextBase context, String id, CancellationToken cancellationToken, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions)
o	at Microsoft.Web.Redis.RedisSessionStateProvider.<GetItemExclusiveAsync>d__19.MoveNext()
o	--- End of stack trace from previous location where exception was thrown ---
o	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
o	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
o	at Microsoft.AspNet.SessionState.SessionStateModuleAsync.<GetSessionStateItemAsync>d__74.MoveNext()
o	--- End of stack trace from previous location where exception was thrown ---
o	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
o	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
o	at Microsoft.AspNet.SessionState.SessionStateModuleAsync.<AcquireStateAsync>d__65.MoveNext()
o	--- End of stack trace from previous location where exception was thrown ---
o	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
o	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
o	at Microsoft.AspNet.SessionState.TaskAsyncHelper.EndTask(IAsyncResult ar)
o	at Microsoft.AspNet.SessionState.SessionStateModuleAsync.EndAcquireState(IAsyncResult result)
o	at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
o	at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
o	at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

```

This is happening in StackExchangeClientConnection.cs line:189.  The serializedSessionStateItemCollection is non null but the .IsNull property is set to TRUE.

Changing line:179 from

- if (serializedSessionStateItemCollection != null)

to

- if (serializedSessionStateItemCollection != null && !serializedSessionStateItemCollection.IsNull)

fixes the problem.

**Comment by stanleysmall-microsoft** [comment] 2023-09-18 13:26
Closing as a duplicate of #206

**Closed by stanleysmall-microsoft** 2023-09-18 13:26 UTC
