### ISSUE TITLE
This solution is not working for multi server setup in AWS behind Load balancer

### ISSUE THREAD

**Issue by vikashachary** [Azure/aspnet-redis-providers#33] opened 2016-06-28 12:19 UTC
I'm facing problem when I tried to use redis as session session server for the below configuration:
1. Two windows servers hosting same application
2. Elastic load balancer with weighted routing redirects requests to the 2 IIS servers
3. Redis is hosted in AWS elastic-cache and accessible from both servers
4. Redis serves as a session server for 1 server at a time without any issue

for each session 3 keys are created
"{/_kktffpxxxxxxg2xixdnhe}_Write_Lock"
"{/_kktffpxxxxxxg2xixdnhe}_Data"
"{/_kktffpxxxxxxg2xixdnhe}_Internal"

Issue: When 1+ servers try to serve same user, by accessing session from redis at same instance, if 1 server have placed "_Write_Lock" then the other server fails to write the data and after that it cleares the key --> result, the user's next request to any server fails to verify his/her session.

Am i the only one who gets this issue ?? 

Note: With session stickiness enabled in ELB the signout is not intermittent, however that restricts us to take out a server for upgradation without loosing all user sessions for that server.

**Comment by SiddharthChatrolaMs** [comment] 2016-07-08 18:49
In ASP.NET all request should hold lock to session before serving request. So in initial phase of request it gets write lock and then executes the page and then releases the lock. if server 1 has the lock then server 2 will wait until it get lock after server 1 releases it. If it is not happening like this then there is some issue. Can you please provide reproducible app?

**Comment by SiddharthChatrolaMs** [comment] 2016-07-29 17:50
@vikashachary: Please reply

**Comment by damonzero** [comment] 2016-08-10 15:02
You are not the only one.  I think your issue is probably related to this one:
[https://github.com/Azure/aspnet-redis-providers/issues/21](url).  

We plan to solve this problem by using a different session state provider that does not lock Redis data.

**Comment by aravindyeduvaka** [comment] 2019-06-18 21:46
Closing the issue because it was fixed as a part of https://github.com/Azure/aspnet-redis-providers/issues/21

**Closed by aravindyeduvaka** 2019-06-18 21:46 UTC
