### ISSUE TITLE
Overwhelming amount of operations causing timeouts?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [Azure/aspnet-redis-providers#88] opened 2017-10-02 18:23 UTC
Monitoring my azure redis cache i came under a severe high number of cases where the total amount of Gets and Sets are _**X**_ and the total number of commands is 3 _**X**_.

Whenever this discrepancy presents itself, I can go to application insights and see that there was a huge number of timeouts regarding _EVAL_ commands. 

The interesting fact here is that, on non-spike moments, the Gets and Sets are _**Y**_ and total commands equals _**1.5Y**_ and there are no timeouts even if Y is higher than 3_**X**_. In another words, the timeouts happen when the discrepancy between GETS+SETS vs TOTAL COMMANDS is high, and not the absolute number of GETS/SETS/COMMANDS...

Can anyone help me figure this one out?

**Comment by JonCole** [comment] 2017-10-02 20:35
TotalCommands is a count of ALL operations on cache during the past time window, including GET, SET, EVAL, AUTH, PING, PUB/SUB, etc.  So, Total Commands will always be higher than GETs and SETs.  

Also, whenever you get timeouts, the providers are configured to retry by default, so the increase in total commands when you see timeout errors is likely a manifestation of the retries rather than the cause of the timeouts.  The session state provider also uses LUA scripts under the covers, and, for each retry that the provider attempts, it will run the script.  Total commands in Azure Redis is incremented once for the eval command and once for each inner operation that the script runs (e.g. if it runs GETs and SETs as part of the script, then those will be counted as well).  

In general, Timeouts are caused by one of several client-side or server-side issues.  I would suggest that you read through the following articles that explain most of the common issues behind timeouts:

- https://gist.github.com/JonCole/db0e90bedeb3fc4823c2#file-diagnoserediserrors-clientside-md
- https://gist.github.com/JonCole/9225f783a40564c9879d#file-diagnoserediserrors-serverside-md

Also, I highly recommend that you read through the Best Practices doc that I have put together as it may also help you avoid other pitfalls that I have seen in many production systems.

- https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f#file-redis-bestpractices-general-md

**Comment by Leonardo-Ferreira** [comment] 2017-10-02 22:41
what i can't figure out is why this is happening. 
I have a standard 2.5gb cache exclusively to handle user sessions. 
I monitor my Worker and IOCP Threads, and usually it keeps north of 20 (min=100)
The cache has around 3k keys (we're a LOB app and the session lasts for 2h) and the total memory consumed hardly ever passes the 350mb line... 
the avg total commands count for non-spike moments is 30-40k during our busiest hours... 
according to these number i should've been experiencing almost zero timeouts and yet, I see between 5 and 100 erros for every 5 min of business hours usage...

**Comment by lsuarez5280** [comment] 2018-04-09 23:07
Possibly related to StackExchange/StackExchange.Redis/issues/760.

**Comment by SiddharthChatrolaMs** [comment] 2018-12-06 17:22
Closing the issue as there is no issue with Session state provider

**Closed by SiddharthChatrolaMs** 2018-12-06 17:22 UTC
