### ISSUE TITLE
Error: Provider must implement the class 'System.Web.SessionState.SessionStateStoreProviderBase'.

### ISSUE THREAD

**Issue by aparker-cityworks** [Azure/aspnet-redis-providers#104] opened 2018-08-09 15:49 UTC
I had a dev update the package from 2.2.6 to 3.0.2 using Nuget and we are now getting an error in our application:
Provider must implement the class 'System.Web.SessionState.SessionStateStoreProviderBase'.

Any idea what might be causing this?  Rolling back to 2.2.6 fixes the issue.  Are there some other requirements in 3.0.2 that I need to take care of?

**Comment by SiddharthChatrolaMs** [comment] 2018-08-20 18:19
@footcha Thanks for the answer. Closing the issue now

**Closed by SiddharthChatrolaMs** 2018-08-20 18:19 UTC

**Comment by kunjan13** [comment] 2019-06-20 06:08
For me the issue is as it says in the configuration in below line:
 <add name="Session"
         type="Microsoft.AspNet.SessionState.SessionStateModuleAsync, Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
         preCondition="integratedMode" />

does it only supports "integratedMode"? My app is hosted on "classic" app pool. I tried with classic app pool and it gives me same error:
"Provider must implement the class 'System.Web.SessionState.SessionStateStoreProviderBase'".

**Comment by IdanLevi** [comment] 2019-10-03 12:57
@kunjan13 <modules> & <handles> (under system.webserver) are for integrated mode only.
The modules & handlers for classic mode are under:
```
<system.web>
    <HttpModules/>
    <HttpHandlers/>
</system.web>
```

That's why the solution above does not work for you.
