### ISSUE TITLE
Session Related Errors - constant timeouts

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [Azure/aspnet-redis-providers#78] opened 2017-07-24 16:53 UTC
So, i noticed that my app has been failing quite a bit... lots of "500" erros happening... and digging into it, I've noticed, by looking at the azure application insights logs that the problem is happening, not on  on "Eval" commands, specifically:
<img width="818" alt="screen shot 2017-07-24 at 13 43 30" src="https://user-images.githubusercontent.com/5585339/28534205-3cbdb0bc-7076-11e7-84e3-9f71dfaa7160.png">

As far as i could go, i came to the conclusion that this happens when the request first arrives and checks for the session lock. I don't know what/why a Eval operation is issued.

I noticed that this happens in bulk, it's not an isolated event, sprinkled over time, but a batch of 20 to 50 requests that fails on the same point in time sequentially

What can I do about it?!?

**Comment by JonCole** [comment] 2017-07-24 18:26
Timeouts can be caused by client side issues or server side issues and there are ways to figure out which one you are hitting.  I have documented the most common causes here:

CLIENT: https://gist.github.com/JonCole/db0e90bedeb3fc4823c2#file-diagnoserediserrors-clientside-md

SERVER: https://gist.github.com/JonCole/9225f783a40564c9879d#file-diagnoserediserrors-serverside-md

**Comment by Leonardo-Ferreira** [comment] 2017-09-20 19:55
sorry for the delay on this...
well, basically i don't get timeouts on the operations I perform explicitly, e.g Gets, Sets, Deletes and TTL. I only see timeouts happening for "Evals" and i know for sure that there are no explicits evals going on, so i assume that this is because of the session provider...

**Comment by wjdavis5** [comment] 2019-01-25 15:04
Sounds like there is enough evidence to consider using multiple ConnectionMultiplexers for high traffic sites to help alleviate some of these issues.

**Comment by mapalan** [comment] 2020-05-20 05:01
@Leonardo-Ferreira sorry for the delay, is this an issue you are still having?

**Comment by juangabreil** [comment] 2020-11-05 11:59
We have the same issue, redis usage is ok but when it comes to session state provider evals it throws a lot of timeouts when our app service is starting to stress.

**Comment by mcharters** [comment] 2023-09-14 17:54
I know this is an older issue, but it seems to be similar to an issue I'm having now. I'm using the Redis Session State Provider with an Azure web app and an Azure Redis Cache, and see periodic timeouts when the Redis Session State Provider code is running EVAL operations:

> MESSAGE: Timeout performing EVAL (5000ms), next: EVAL, inst: 0, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: redis01-charitycan.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: XXXXXXXXXXXX, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=57,Free=8134,Min=200,Max=8191), v: 2.1.30.38891 (Please take a look at this article for some common client-side issues that can cause timeouts: [https://stackexchange.github.io/StackExchange.Redis/Timeouts)<p>SOURCE](https://stackexchange.github.io/StackExchange.Redis/Timeouts)%3cp%3eSOURCE): StackExchange.Redis<p>FORM: <p>QUERYSTRING: <p>TARGETSITE: T ExecuteSyncImpl[T](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1[T], StackExchange.Redis.ServerEndPoint)<p>STACKTRACE:    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2616
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1153
   at Microsoft.Web.Redis.StackExchangeClientConnection.<>c__DisplayClass7_0.<Eval>b__0() in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\Shared\StackExchangeClientConnection.cs:line 68
   at Microsoft.Web.Redis.StackExchangeClientConnection.OperationExecutor(Func`1 redisOperation) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\Shared\StackExchangeClientConnection.cs:line 95
   at Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func`1 redisOperation) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\Shared\StackExchangeClientConnection.cs:line 118
   at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\Shared\StackExchangeClientConnection.cs:line 68
   at Microsoft.Web.Redis.RedisConnectionWrapper.TryCheckWriteLockAndGetData(Object& lockId, ISessionStateItemCollection& data, Int32& sessionTimeout) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:line 232
   at Microsoft.Web.Redis.RedisSessionStateProvider.GetItemFromSessionStore(Boolean isWriteLockRequired, HttpContextBase context, String id, CancellationToken cancellationToken, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:line 291
   at Microsoft.Web.Redis.RedisSessionStateProvider.<GetItemAsync>d__19.MoveNext() in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.<GetSessionStateItemAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.<AcquireStateAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.EndAcquireState(IAsyncResult result)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

The strange thing is that these issues are happening hourly - I don't know whether that's an issue with the hardware it's running on, but most of the time everything runs completely smoothly. Then every hour, like clockwork, I get a flurry of these timeouts. I'm working with Azure folks on seeing if there's a solution that they can help me with, but figured I'd post here as well in case anyone has any insights.

**Comment by philon-msft** [comment] 2023-09-15 15:55
Hi @mcharters , it looks like your cache is impacted by an Azure Cache issue where periodic OS background jobs saturate the CPU once an hour, causing Redis commands to timeout. We're working on a fix, but meanwhile there are a couple mitigations: 
- Your cache is scheduled to receive an update this weekend, which will reinitialize the cache nodes. This should stop the CPU saturation for a while, but eventually it will start occurring again. 
- Upgrading from the C1 cache SKU to C2 would give each cache node two cores, and eliminate the competition for CPU resources between the Redis server process and background OS processes

**Comment by mcharters** [comment] 2023-09-15 16:06
@philon-msft phew, thank you! I have been dealing with this issue for months and I thought I was going bananas. Glad to hear it's being worked on!

I can upgrade to a C2 for now but don't really need that much compute power typically - is there any way to track the status of the Azure Cache issue to know when it's been fixed so I can downgrade afterwards?

**Comment by philon-msft** [comment] 2023-09-15 16:10
@mcharters we're hoping to have a fix deployed by the end of October - feel free to confirm with me at that time (or optimistically scale back down to C1)

**Comment by stanleysmall-microsoft** [comment] 2023-11-13 21:03
The fix should be deployed by now - closing the issue.

**Closed by stanleysmall-microsoft** 2023-11-13 21:03 UTC
