### ISSUE TITLE
Whats the logic for update the Web.config on Updates

### ISSUE THREAD

**Issue by ricardopolo** [Azure/aspnet-redis-providers#9] opened 2015-09-21 16:45 UTC
I have this in my web.config
````
    <sessionState mode="Custom" customProvider="SessionStateStore">
      <providers>
        <add port="" applicationName="SigntulSession" name="SessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="localhost" accessKey="" ssl="false" throwOnError="true" />
      </providers>
    </sessionState>
````

Always when update the NuGet I get the example   <sessionState mode="Custom" customProvider="MySessionStateStore"> in my web.config and the app stops working until I deleted

So whats the logic for that and how can avoid this?

Thank you

**Comment by JonCole** [comment] 2015-09-21 17:03
This appears to be a duplicate of Issue #7.

**Closed by JonCole** 2015-09-21 17:03 UTC
