### ISSUE TITLE
3.0.1 is incomplete strong name signature

### ISSUE THREAD

**Issue by shibayan** [Azure/aspnet-redis-providers#103] opened 2018-06-14 03:01 UTC
Version 3.0.1 is not a signature of a strong name, it is delayed signed, so the assembly can not be read correctly.

>ASPNETCOMPILER : error ASPCONFIG: Could not load file or assembly 'Microsoft.Web.RedisSessionStateProvider, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by chancedj** [comment] 2018-06-14 14:11
We are seeing this issue as well. Was watching the issues to see if it was just us or if it was others.

**Comment by uwcanada** [comment] 2018-06-14 17:57
Seeing the same thing...

**Comment by JonCole** [comment] 2018-06-14 18:01
Thanks for the heads up - we will investigate ASAP.  I have hidden this package version for now.

**Comment by SiddharthChatrolaMs** [comment] 2018-06-14 18:37
@shibayan @chancedj @uwcanada I have tried below combination but i am not able to reproduce this locally.
1) ASP.NET app with .net 4.5.2 and VS 2015
2) ASP.NET app with .net 4.5.2 and VS 2017
3) ASP.NET app with .net 4.6.2 and VS 2017

Can anyone of you share a small repro with me?

**Comment by uwcanada** [comment] 2018-06-14 18:42
Try in release mode

**Comment by SiddharthChatrolaMs** [comment] 2018-06-14 18:50
@uwcanada No luck with release mode as well :( Issue is with package signing or dll signing? Also, dll's are signed with sha2

**Comment by chancedj** [comment] 2018-06-14 18:55
windows 10
Visual studio 2017
Web Forms project

here is the packages.config (the only difference being i rolled back to the previous version of this package)

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AspNet.ScriptManager.jQuery" version="3.3.1" targetFramework="net462" />
  <package id="ckeditor-standard-all" version="4.5.1" targetFramework="net462" />
  <package id="IdentityModel" version="2.7.0" targetFramework="net452" />
  <package id="jQuery" version="3.3.1" targetFramework="net462" />
  <package id="Microsoft.AspNet.SessionState.SessionStateModule" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Logging" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net452" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.1.3" targetFramework="net452" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security.Cookies" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Web.RedisSessionStateProvider" version="2.2.6" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net462" />
  <package id="Owin" version="1.0" targetFramework="net462" />
  <package id="qTip2" version="2.2.1" targetFramework="net452" />
  <package id="StackExchange.Redis.StrongName" version="1.2.6" targetFramework="net462" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.4.403061554" targetFramework="net452" />
</packages>

I can also strip out the necessary pieces of web config and post that too if you want.  There's some that are still 452, but the project is in the process of being upgraded to 4.6.2 - so i haven't gotten to all of them yet.

If you still have no luck i can see about stripping everything down except for 1 HelloWorld form or something and see if i can reproduce there, and then send to you.

**Comment by SiddharthChatrolaMs** [comment] 2018-06-14 19:38
@chancedj @uwcanada Thank you for the help. Found the issue and fixing it

**Comment by chancedj** [comment] 2018-06-14 19:40
Awesome, thanks!

**Comment by uwcanada** [comment] 2018-06-14 19:41
Yes, thank you!

**Comment by SiddharthChatrolaMs** [comment] 2018-06-19 21:11
@shibayan @chancedj @uwcanada I have released new NuGet packages with fix. Please verify and confirm here.  

https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/3.0.2
https://www.nuget.org/packages/Microsoft.Web.RedisOutputCacheProvider/2.0.1-preview

**Comment by shibayan** [comment] 2018-06-20 01:54
I confirmed that the signature has been fixed. Thank you!

**Comment by uwcanada** [comment] 2018-06-20 15:34
When I installed the original 3.x version, it worked in debug mode but
would fail with the signing problems when doing a Release version. Now it
doesn't work at all.

Out of no where, I now get this after install of the new 3.x version:



Here's the key-redacted config I'm using:



Any ideas?

Thanks
Shane

**Comment by chancedj** [comment] 2018-06-20 17:34
just checked.  got the new strongname and the new provider.  no more error.  no more binding redirect necessary either in web.config for strongname.

**Comment by SiddharthChatrolaMs** [comment] 2018-08-20 18:18
Closing this as issue is resolved

**Closed by SiddharthChatrolaMs** 2018-08-20 18:18 UTC
