### ISSUE TITLE
System.IO.FileNotFoundException in Microsoft.Web.RedisOutputCacheProvider.dll

### ISSUE THREAD

**Issue by sorcer1** [Azure/aspnet-redis-providers#37] opened 2016-07-27 08:16 UTC
Hello,

I'm trying to use your provider in my mvc project but when i try to debug my contoller action i see the caching is not working.

And when i read my debug output i can see this error :
Exception thrown: 'System.IO.FileNotFoundException' in Microsoft.Web.RedisOutputCacheProvider.dll

How can i know what is missing ?

This is my caching web.config section :

```
<caching>
      <outputCache defaultProvider="MyRedisOutputCache" enableOutputCache="true">
          <providers>
              <add name="MyRedisOutputCache" host="192.168.100.168" port="6379" databaseId="2"
                        accessKey="" applicationName="LocalOutputCache" ssl="false"
                        type="Microsoft.Web.Redis.RedisOutputCacheProvider, Microsoft.Web.RedisOutputCacheProvider" />
          </providers>
      </outputCache>
      <outputCacheSettings>
        <outputCacheProfiles>
          <add name="Standard" duration="3600" varyByParam="*" />
          <add name="Static" duration="43200" varyByParam="None" />
        </outputCacheProfiles>
      </outputCacheSettings>
    </caching>
```

Thanks.

**Comment by SiddharthChatrolaMs** [comment] 2016-07-27 21:55
This is duplicate of issue https://github.com/Azure/aspnet-redis-providers/issues/15

**Closed** 2016-07-27 21:55 UTC
Labels: duplicate
