### ISSUE TITLE
Use new StackExchange.Redis [strong-named] instead of StackExchange.Redis.StrongName

### ISSUE THREAD

**Issue by evertonmc** [Azure/aspnet-redis-providers#110] opened 2018-10-24 12:57 UTC
https://github.com/StackExchange/StackExchange.Redis/blob/dd0ee6096930cbb6be9ee8fdd59984ded098eac0/docs/ReleaseNotes.md#20495

**Comment by JonCole** [comment] 2018-10-24 16:19
Duplicate of #107

**Closed by JonCole** 2018-10-24 16:19 UTC
