### ISSUE TITLE
RedisSessionstate Provider gives more Response Size while saving 25kb file data in session

### ISSUE THREAD

**Issue by saranyarajendrancw** [Azure/aspnet-redis-providers#191] opened 2023-06-02 17:38 UTC
We use the Redis Cache package library - SE.Redis-v2.6.96.30123 , Microsoft.Web.RedisSessionStateProvider – 5.0.0 , ASP.NET 4.8 – VB , to set and get session objects.
We save 25kB size of excel data in bytes format in session, when setting the data in redis session it takes about 1.25 MB size and after that it shows 25KB size of data.

What is the reason for spike while writing the data in session?

**Comment by stanleysmall-microsoft** [comment] 2023-06-05 13:08
Closing as a duplicate of #192

**Closed by stanleysmall-microsoft** 2023-06-05 13:08 UTC
