### ISSUE TITLE
Incorrect assembly version on RedisSessionStateProvider 5.0.0

### ISSUE THREAD

**Issue by DustinTheDev** [Azure/aspnet-redis-providers#186] opened 2023-03-22 15:46 UTC
The RedisSessionStateProvider 5.0.0 package [published to nuget](https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/5.0.0) has an incorrect assembly version of 1.1.0.0 and is not strongly signed:
```
Microsoft.Web.RedisSessionStateProvider, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
```
This is a departure from the previous 4.0.1 package release [published to nuget](https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/4.0.1):
```
Microsoft.Web.RedisSessionStateProvider, Version=4.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```

**Comment by stanleysmall-microsoft** [comment] 2023-06-05 22:54
Closing as a duplicate of issue #183

**Closed by stanleysmall-microsoft** 2023-06-05 22:54 UTC
