### ISSUE TITLE
Could not load type 'Microsoft.Web.Redis.RedisSessionStateProvider'.

### ISSUE THREAD

**Issue by gonace** [Azure/aspnet-redis-providers#15] opened 2015-12-08 11:23 UTC
Hi
I'm having problems getting this nuget to work, I've reinstalled the nuget multiple times but still getting the same " Could not load type 'Microsoft.Web.Redis.RedisSessionStateProvider'." error.

Any idea why?

**Comment by SiddharthChatrolaMs** [comment] 2016-03-09 02:17
Can you copy paste complete stack trace here?

**Comment by vijishine** [comment] 2016-03-13 20:50
I also face the issue. have tried uninstalling and res-installing packages for multiple times yet the same issue **Could not load type 'Microsoft.Web.Redis.RedisSessionStateProvider'**. any solution is appreciated..

**Comment by SiddharthChatrolaMs** [comment] 2016-03-15 21:18
Please send complete stack trace along with details about what version of VS you are using with which kind of ASP.NET project and what version of .NET you are using.

**Comment by gmalla** [comment] 2016-04-11 17:54
Below is the stack trace from the reproduced error. Hope this helps: 

```
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1857
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 80
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 886
   at Microsoft.Web.Redis.StackExchangeClientConnection.<>c__DisplayClass4.<Eval>b__3() in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:line 117
   at Microsoft.Web.Redis.StackExchangeClientConnection.RetryForScriptNotFound(Func`1 redisOperation) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:line 133
   at Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func`1 redisOperation) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:line 155
   at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:line 117
   at Microsoft.Web.Redis.RedisConnectionWrapper.Set(ISessionStateItemCollection data, Int32 sessionTimeout) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:line 133
   at Microsoft.Web.Redis.RedisSessionStateProvider.SetAndReleaseItemExclusive(HttpContext context, String id, SessionStateStoreData item, Object lockId, Boolean newItem) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:line 408
   at System.Web.SessionState.SessionStateModule.OnReleaseState(Object source, EventArgs eventArgs)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by robs** [comment] 2016-04-29 15:45
@gmalla I was getting that error locally. Opening port 6380 on the firewall resolved it.

I was getting the op's error as well having added via nuget and pushing changes for azure kudu sync to grab.

Check your csproj file to make sure the reference was added - mine wasn't.
All I did was close then re-open the solution and rebuilt which added the reference in the csproj

    <Reference Include="Microsoft.Web.RedisSessionStateProvider, Version=2.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.Web.RedisSessionStateProvider.2.2.0\lib\net40\Microsoft.Web.RedisSessionStateProvider.dll</HintPath>
      <Private>True</Private>
    </Reference>

Worked fine after that push.

**Comment by SiddharthChatrolaMs** [comment] 2016-07-27 21:40
@gonace , @vijishine, @gmalla: Hope above comment from @robs has resolved your issue. Closing the bug now.

**Closed by SiddharthChatrolaMs** 2016-07-27 21:40 UTC

**Comment by sorcer1** [comment] 2016-07-28 07:40
I'm sorry but you closed my issue (#37) but i think there is not the same.
In my csproj i have the reference but i have still the error.
The exception was thrown in the RedisOutputCacheProvider and not in my project, so i can't catch them.
Can you help me to find the missing file ?

My error debug console : Exception thrown: 'System.IO.FileNotFoundException' in Microsoft.Web.RedisOutputCacheProvider.dll

**Comment by Kesmy** [comment] 2016-08-05 15:00
@SiddharthChatrolaMs This problem is not resolved. The type load error has nothing to do with the connection error.

**Comment by ingig** [comment] 2020-09-08 17:55
I had this problem, it turns out the module definition for session was out of date in my web.config. 

When I changed it to following, everything worked

  ```
<modules>
  <remove name="Session" />
  <add name="Session" type="Microsoft.AspNet.SessionState.SessionStateModuleAsync, Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" preCondition="managedHandler" />
  </modules>
```

The definition I had before was as following
`  <add name="Session" type="System.Web.SessionState.SessionStateModule" />`
